baseURL = 'https://codeql-agent-project.github.io/codeql-cheatsheet/'
languageCode = 'en-us'
title = 'CodeQL Cheatsheets'
relativeURLs = "true"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
