baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'CodeQL Cheatsheets'

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
