name: Contribute Check

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - "add-queries"

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: List all added files
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "$file was added"
          done

      - name: List all modified files
        run: |
          for file in ${{ steps.changed-files.outputs.modified_files }}; do
            echo "$file was added"
          done